[package]
edition = "2021"
name = "node_sdl"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-derive = "3.5.0"
sdl2 = { version = "0.38.0", features = ["mixer", "unsafe_textures"] }

[dependencies.napi]
version = "3.12.0"
features = ["napi10"]

[build-dependencies]
napi-build = "2.3.1"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
